---
 - name: Install IIS
   ansible.windows.win_feature:
     name: Web-Server
     include_sub_features: yes
     include_management_tools: yes
     state: present

 - name: Add a new html page
   ansible.windows.win_copy:
     src: index2.html
     dest: C:\inetpub\wwwroot

 - name: Log successful access
   win_shell: Select-String -Path C:\inetpub\logs\LogFiles\W3SVC1\u_ex*.log -Pattern '(/index2.html)[a-zA-Z0-9/+:;.\-() ]*200' | Out-File -FilePath C:\Windows\Logs\web_200.log -Encoding utf8

 - name: Fetch success log file
   fetch:
     src: C:\Windows\Logs\web_200.log
     dest: /home/nimda/ics0020-labs-outcome/lab01-win-index2.html
     flat: yes

 - name: Log unsuccessful access
   win_shell: Select-String -Path C:\inetpub\logs\LogFiles\W3SVC1\u_ex*.log -Pattern '(/index2.htm)[a-zA-Z0-9/+:;.\-() ]*404' | Out-File -FilePath C:\Windows\Logs\web_404.log -Encoding utf8

 - name: Fetch 404 log file
   fetch:
     src: C:\Windows\Logs\web_404.log
     dest: /home/nimda/ics0020-labs-outcome/lab01-win-not.existing
     flat: yes