---
- name: change hostname
  ansible.windows.win_hostname:
    name: windows
  register: res

- name: reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: change password
  ansible.windows.win_user:
    name: nimda
    state: present
    password: "kala..11"
    groups_action: add

- name: Create detimil
  ansible.windows.win_user:
    name: detimil
    groups_action: add

- name: copy publickey
  ansible.windows.win_copy:
    src: "/home/{{ admin_win }}/.ssh/{{ ssh_file }}.pub"
    dest: "C:\\ProgramData\\ssh\\administrators_authorized_keys"

- name: create ssh directory
  ansible.windows.win_file:
    path: C:\\Users\\{{ user_win }}\\.ssh
    state: directory

- name: copy publickey to detimil
  ansible.windows.win_copy:
    src: "/home/{{ admin_win }}/.ssh/{{ ssh_file }}.pub"
    dest: "C:\\Users\\{{ user_win }}\\.ssh\\authorized_keys"