---
- name: Set authorized public key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/home/{{ item }}/.ssh/id_ed25519.pub') }}"
  with_items:
    - "nimda"
    - "detimil"
