---
#Log attempts of changing or resetting password
 - name: Log "change or reset password" attempts
   win_shell: Get-WinEvent -FilterHashtable @{LogName = 'Security'; ID = 4723,4724} | Out-FIle -FilePath C:\Windows\Logs\change_pswd.log -Encoding utf8

 - name: Fetch "change or reset password" log file
   fetch:
     src: C:\Windows\Logs\change_pswd.log
     dest: /home/nimda/ics0020-labs-outcome/lab01-win-pwd.change
     flat: yes

#Log failed login attempts

 - name: Log failed login attempts
   win_shell: Get-WinEvent -FilterHashtable @{LogName = 'Security'; ID = 4625} | Out-FIle -FilePath C:\Windows\Logs\failed_login.log -Encoding utf8

 - name: Fetch log file of failed logins
   fetch:
     src: C:\Windows\Logs\failed_login.log
     dest: /home/nimda/ics0020-labs-outcome/lab01-win-login.failed 
     flat: yes

#Log successful logins

 - name: Log successful login attempts
   win_shell: Get-WinEvent -FilterHashtable @{LogName = 'Security'; ID = 4624} | Out-FIle -FilePath C:\Windows\Logs\successful_login.log -Encoding utf8

 - name: Fetch log file of successful logins
   fetch:
     src: C:\Windows\Logs\successful_login.log
     dest: /home/nimda/ics0020-labs-outcome/lab01-win-login.successful
     flat: yes

#Log all services stopped since last boot

 - name: Log all services stopped since last boot
   win_shell: Get-WinEvent -FilterHashtable @{LogName = 'System'; ID = 7036; Data = "stopped"} | Where-Object {$_.timecreated -gt (Get-CimInstance win32_Operatingsystem).lastbootuptime} | Out-File -FilePath C:\Windows\Logs\stopped_service.log -Encoding utf8

 - name: Log all services unexpectedly terminated since last boot
   win_shell: Get-WinEvent -FilterHashtable @{LogName = 'System'; ID = 7034} | Where-Object {$_.timecreated -gt (Get-CimInstance win32_Operatingsystem).lastbootuptime} | Out-FIle -FilePath C:\Windows\Logs\stopped_service.log -Encoding utf8 -Append

 - name: Fetch log file of stopped services
   fetch:
     src: C:\Windows\Logs\stopped_service.log
     dest: /home/nimda/ics0020-labs-outcome/lab01-win-services.stopped
     flat: yes