---
 - name: Change hostname of Windows
   ansible.windows.win_hostname:
     name: windows
   register: res

 - name: Reboot Windows
   ansible.windows.win_reboot:
   when: res.reboot_required

 - name: Change password on Windows
   ansible.windows.win_user:
     name: nimda
     state: present
     password: "{{ win_pass }}"
     groups_action: add

 - name: Create detimil on Windows
   ansible.windows.win_user:
     name: detimil
     groups_action: add

 - name: Copy public key to the administrative nimda user
   ansible.windows.win_copy:
     src: "/home/{{ admin_win }}/.ssh/{{ ssh_file }}.pub"
     dest: "C:\\ProgramData\\ssh\\administrators_authorized_keys"

 - name: Ensure adminsitrative detimil user has .ssh folder
   ansible.windows.win_file:
     path: "C:\\Users\\{{ user_win }}\\.ssh"
     state: directory

 - name: Copy public key to the regular detimil user
   ansible.windows.win_copy:
     src: "/home/{{ admin_win }}/.ssh/{{ ssh_file }}.pub"
     dest: "C:\\Users\\{{ user_win }}\\.ssh\\authorized_keys"