---
- name: Create a keypair
  user:
    name: nimda
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    force: no

- name: Create .ssh directory for the regular user
  file:
    path: /home/detimil/.ssh
    state: directory
    owner: "detimil"
    group: "detimil"
    mode: '0751'

- name: Copy SSH keys
  copy:
    remote_src: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "detimil"
    group: "detimil"
    mode: "{{ item.mode }}"
  with_items:
    - { src: '/home/nimda/.ssh/id_ed25519', dest: '/home/detimil/.ssh/id_ed25519', mode: '0600' }
    - { src: '/home/nimda/.ssh/id_ed25519.pub', dest: '/home/detimil/.ssh/id_ed25519.pub', mode: '0644' }

...