---
- name: acquire certificate
  win_shell: New-SelfSignedCertificate -DnsName "localhost" -KeyLength 4096 -CertStoreLocation cert:\LocalMachine\My -NotAfter (Get-Date).AddYears(1)

- name: get certificate
  win_shell: Get-ChildItem cert:\LocalMachine\My | Where-Object {$_.subject -eq 'CN=localhost'} | Out-File -FilePath C:\Windows\Logs\cert.log

- name: get certificate hash
  win_shell: Select-String -Path C:\Windows\Logs\cert.log -Pattern '^[^a-z\-= ][A-Z0-9]*' | Out-File -FilePath C:\Windows\Logs\cert_hash.log

- name: register certificate hash
  win_shell: Get-Content -Path C:\Windows\Logs\cert_hash.log | Foreach-Object {$_.split("  ")[0]}
  register: certificate_hash

- name: SSL bind
  win_iis_webbinding:
    name: Default Web Site
    protocol: https
    port: 443
    ip: '*'
    certificate_hash: "{{ certificate_hash.stdout_lines[1].split(':')[3] }}"
    state: present